# Generated by Django 5.2.8 on 2025-11-11 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('category', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('livros', 'Livros'), ('material_escolar', 'Material Escolar'), ('moveis', 'Móveis'), ('esportes', 'Esportes'), ('moda', 'Moda'), ('servicos', 'Serviços'), ('outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('condition', models.CharField(choices=[('novo', 'Novo'), ('usado_otimo', 'Usado - Ótimo Estado'), ('usado_bom', 'Usado - Bom Estado'), ('usado_regular', 'Usado - Regular Estado'), ('usado', 'Usado'), ('nao_especificado', 'Não especificado')], max_length=20, verbose_name='Condição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('sold', 'Vendido'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='Status')),
                ('location', models.CharField(choices=[('cruz_das_almas', 'Campus Cruz das Almas'), ('feira_de_santana', 'Campus Feira de Santana'), ('santo_antonio', 'Campus Santo Antônio de Jesus'), ('amargosa', 'Campus Amargosa')], max_length=50, verbose_name='Campus')),
                ('views', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Imagem')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens dos Produtos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
