# Generated by Django 5.2.8 on 2025-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('darcy', 'Campus Darcy Ribeiro'), ('fcte', 'Campus FCTE'), ('ceilandia', 'Campus Ceilândia'), ('planaltina', 'Campus Planaltina'), ('gama', 'Campus Gama')], max_length=50, verbose_name='Campus'),
        ),
    ]
