# Generated by Django 5.2.8 on 2025-11-11 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('course', models.CharField(blank=True, max_length=200, verbose_name='Curso')),
                ('campus', models.CharField(choices=[('cruz_das_almas', 'Campus Cruz das Almas'), ('feira_de_santana', 'Campus Feira de Santana'), ('santo_antonio', 'Campus Santo Antônio de Jesus'), ('amargosa', 'Campus Amargosa')], max_length=50, verbose_name='Campus')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Avaliação')),
                ('review_count', models.IntegerField(default=0, verbose_name='Número de Avaliações')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total de Vendas')),
                ('member_since', models.DateTimeField(auto_now_add=True, verbose_name='Membro desde')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
